project:
  type: website
  output-dir: _site

website:
  title: "Harbinger Route Calculator"
  description: "High-Performance Telemetry Engine Documentation"
  search: true
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: "Engine & Logic"
      - href: about.qmd
        text: "Architecture & Stack"

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true
    toc-depth: 3
    code-fold: show
    code-copy: true
