website:
  title: "Harbinger Route Calculator"
  description: "High-Performance Telemetry Engine Documentation"
  search: true
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: "Engine & Logic"
      - href: about.qmd
        text: "Architecture & Stack"
    right:
      - icon: github
        href: https://github.com/leo3457/Route_Calculator

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true
    toc-depth: 3
    code-fold: show
    code-copy: true